name: Building TWRP Android-12.1

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  watch:
    types: [started]

env:
  MANIFEST: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
  DEVICE: fog
  DT_LINK: https://github.com/boedhack99/device_xiaomi_fog-TWRP -b twrp-12.1
  DT_PATH: device/xiaomi/fog
  KERNEL_LINK: https://github.com/dblenk-project/kernel_xiaomi_fog_header
  KERNEL_PATH: kernel/xiaomi/fog
  REVISION: lineage-20
  TARGET: bootimage
  ZIP_NAME: TWRP_fog_A12.1.zip
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Initializing environment
         run: |
            sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
            docker rmi `docker images -q`
            sudo apt-get remove account-plugin-facebook account-plugin-flickr account-plugin-twitter account-plugin-windows-live aisleriot brltty duplicity empathy empathy-common example-content gnome-accessibility-themes gnome-contacts gnome-mahjongg gnome-mines gnome-orca gnome-screensaver gnome-sudoku gnome-video-effects landscape-common libreoffice-avmedia-backend-gstreamer libreoffice-base-core libreoffice-calc libreoffice-common libreoffice-core libreoffice-draw libreoffice-gnome libreoffice-gtk libreoffice-impress libreoffice-math libreoffice-ogltrans libreoffice-pdfimport libreoffice-style-galaxy libreoffice-style-human libreoffice-writer libsane libsane-common python3-uno rhythmbox rhythmbox-plugins rhythmbox-plugin-zeitgeist sane-utils shotwell shotwell-common telepathy-gabble telepathy-haze telepathy-idle telepathy-indicator telepathy-logger telepathy-mission-control-5 telepathy-salut totem totem-common totem-plugins printer-driver-brlaser printer-driver-foo2zjs printer-driver-foo2zjs-common printer-driver-m2300w printer-driver-ptouch printer-driver-splix
            git config --global user.name "infinixs5lite"
            git config --global user.email "kelvinchinedu97@gmail.com"         
            sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mysql* php* 
            sudo -E apt-get clean 
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python3 gcc clang libssl-dev rsync flex curl  bison aria2
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
            sudo chmod a+rx /usr/local/bin/repo
            
       - name: Sync TWRP A12.1 source and device tree and pick some gerrit patches
         run: |
             mkdir work
             cd work
             repo init --depth=1 -u $MANIFEST --partial-clone --clone-filter=blob:limit=10M --groups=all,-notdefault,-device,-darwin,-x86,-mips
             repo sync -j4
             git clone $DT_LINK --depth=1 --single-branch $DT_PATH
             git clone $KERNEL_LINK --depth=1 $KERNEL_PATH

       - name: Set Swap Space
         uses: pierotofy/set-swap-space@master
         with:
          swap-size-gb: 20
             
       - name: Building TWRP
         run: |
              cd work
              . build/envsetup.sh 
              lunch twrp_$DEVICE-eng 
              rm -rf .repo/
              mka $TARGET
             
       - name: Uploading boot image
         run: |
              cd work/out/target/product/$DEVICE
              sudo zip -r9 $ZIP_NAME boot.img
              ./transfer wet $ZIP_NAME
              ./transfer wet boot.img
